In [3]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


***Welcome to Numpy***

In [4]:
import numpy
print(numpy.__version__)

2.1.3


In [5]:
import numpy as np

In [6]:
myarr = np.array([[1,2,4]], np.int8)

In [7]:
myarr[0,1]

np.int8(2)

In [8]:
myarr.shape

(1, 3)

In [9]:
myarr.dtype

dtype('int8')

In [10]:
myarr[0,1] = 8

In [11]:
myarr

array([[1, 8, 4]], dtype=int8)

#Array creation methods

In [12]:
listarr = np.array([[1,2,3],[4,5,6],[7,4,4]])

In [13]:
listarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 4, 4]])

In [14]:
zeros = np.zeros((2,3))

In [15]:
rng = np.arange(4,9)
print(rng)

[4 5 6 7 8]


In [16]:
lp = np.linspace(1,5,12)

In [17]:
lp

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [18]:
idn = np.identity(6)

In [19]:
idn

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [20]:
arr = np.arange(66)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65])

In [22]:
arr = arr.reshape(3,22)

In [23]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
        38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
        60, 61, 62, 63, 64, 65]])

In [24]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65])

In [25]:
arr.shape

(3, 22)

In [26]:
arr.shape

(3, 22)

In [27]:
arr.shape

(3, 22)

In [28]:
id = np.linspace(1,6,4)

In [29]:
id

array([1.        , 2.66666667, 4.33333333, 6.        ])

In [30]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [31]:
ar = np.array(x)

In [32]:
ar.sum(axis=0)

array([12,  8,  9])

In [33]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [34]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [35]:
for i in ar.flat:
    print(i,end=" ")

1 2 3 4 5 6 7 1 0 

In [36]:
one = np.array([1,2,3,5,8])

In [37]:
one.argmax()

np.int64(4)

In [38]:
one.argmin()

np.int64(0)

In [39]:
one.argsort()

array([0, 1, 2, 3, 4])

In [40]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [41]:
ar.argmin()

np.int64(8)

In [42]:
ar.argmax()

np.int64(6)

In [43]:
ar.argmax(axis=1)

array([2, 2, 0])

In [44]:
ar.argmin(axis=0)

array([0, 2, 2])

In [45]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [46]:
ar2 = np.array([[1,2,0],
                [0,2,2],
                [5,3,1]])

In [47]:
ar+ar2

array([[ 2,  4,  3],
       [ 4,  7,  8],
       [12,  4,  1]])

In [48]:
ar*ar2

array([[ 1,  4,  0],
       [ 0, 10, 12],
       [35,  3,  0]])

In [49]:
np.sqrt(ar2)

array([[1.        , 1.41421356, 0.        ],
       [0.        , 1.41421356, 1.41421356],
       [2.23606798, 1.73205081, 1.        ]])

In [50]:
np.where(ar2==5)

(array([2]), array([0]))

In [51]:
np.count_nonzero(ar2)

7

In [52]:
np.nonzero(ar2)

(array([0, 0, 1, 1, 2, 2, 2]), array([0, 1, 1, 2, 0, 1, 2]))

In [53]:
ar2[1,2] = 0

In [54]:
np.nonzero(ar2)

(array([0, 0, 1, 2, 2, 2]), array([0, 1, 1, 0, 1, 2]))

In [60]:
import sys

In [55]:
py_ar = [0,2,55,4]

In [57]:
np_ar = np.array(py_ar)

In [62]:
sys.getsizeof(1)*len(py_ar)

112

In [64]:
np_ar.itemsize*np_ar.size

32

In [65]:
np_ar.tolist()

[0, 2, 55, 4]